server:
  port: 0

core-banking-service: http://localhost:8080

spring:
  application:
    name: account-bank-service
  datasource:
    url: jdbc:h2:file:/database/ACCOUNT;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:ACCOUNT
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    enabled: true

flyway:
  user: sa
  password: password
  schemas: core_bank-schema
#  url: jdbc:h2:mem:ACCOUNT
  url: jdbc:h2:file:/database/ACCOUNT

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    preferIpAddress: true