spring:
  application:
    name: account-bank-service
  datasource:
    url: jdbc:h2:file:/database/ACCOUNT;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:ACCOUNT
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    enabled: true
    cloud:
      stream:
        bindings:
          getAccounts-in-0:
            destination: account
            binder: nats1
          getAccounts-out-0:
            destination: client
            binder: nats1
        binders:
          nats1:
            type: nats
            environment:
              nats:
                spring:
                  cloud:
                    stream:
                      binder:
                        server: nats://localhost:4222
#nats:
#  spring:
#    server: nats://localhost:4222

flyway:
  user: sa
  password: password
  schemas: core_bank-schema
#  url: jdbc:h2:mem:ACCOUNT
  url: jdbc:h2:file:/database/ACCOUNT

