spring:
  datasource:
#    url: jdbc:h2:file:/database/core_rfid_bank
    url: jdbc:h2:mem:CARD
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  cloud:
    stream:
      definition: cardTransfer,updateCardTransfer
      bindings:
        cardTransfer-in-0:
          destination: atm
          group: transactionInitAtm
        cardTransfer-out-0:
          destination: transfer
        updateCardTransfer-in-0:
          destination: transfer
          group: updateCardTransfer
      rabbit:
        bindings:
          transactionStatus-in-0:
            consumer:
#              bindQueue: false
#              declareExchange: false
              queueNameGroupOnly: true
              exchangeType: direct
              bindingRoutingKey: transactionInitAtm
          sendTransfer-out-0:
            producer:
#              bindQueue: false
#              declareExchange: false
              queueNameGroupOnly: true
              exchangeType: direct
              routingKeyExpression: '''cardTransferInit'''
          updateCardTransfer-in-0:
            producer:
#              bindQueue: false
#              declareExchange: false
              queueNameGroupOnly: true
              exchangeType: direct
              bindingRoutingKey: updateCardTransfer

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

myhost.name: localhost
