spring:
  datasource:
#    url: jdbc:h2:file:/database/core_rfid_bank
    url: jdbc:h2:mem:CLIENT
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    enabled: true
  cloud:
    stream:
      definition: getAccount;sendClientID
      bindings:
        getAccount-in-0:
          destination: client
          group: accounts
        sendClientID-out-0:
          destination: client
      rabbit:
        bindings:
          getAccount-in-0:
            consumer:
              bindQueue: false
              declareExchange: false
              queueNameGroupOnly: true
              exchangeType: direct
              bindingRoutingKey: accounts
          sendClientID-out-0:
            producer:
              bindQueue: false
              declareExchange: false
              queueNameGroupOnly: true
              exchangeType: direct
              routingKeyExpression: '''accountsID'''
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest


flyway:
  user: sa
  password: password
  schemas: client_bank-schema
  url: jdbc:h2:mem:CLIENT
