spring:
  datasource:
#    url: jdbc:h2:file:/database/core_rfid_bank
    url: jdbc:h2:mem:CLIENT
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    enabled: true

  cloud:
    stream:
      function:
        definition: getAccount;getAccounts
      bindings:
        getAccount-in-0:
          destination: client
          binder: nats
          group: a
        getAccounts-out-0:
          destination: account
          binder: nats
nats:
  spring:
    server: nats://localhost:4222

flyway:
  user: sa
  password: password
  schemas: client_bank-schema
  url: jdbc:h2:mem:CLIENT

